/**
 * Preset Scenarios — 6 named parameter configurations
 *
 * Each preset loads a complete set of simulation parameters.
 * All parameters remain editable after loading.
 */

export const PRESETS = {
  soft_landing: {
    id: 'soft_landing',
    name: 'Soft Landing',
    message: 'Managed transition with proactive policy and equitable access',
    description: 'Gradual adoption with strong retraining, moderate UBI, and broad AI access.',
    params: {
      adoptionRate: 45,
      adoptionCurve: 'gradual',
      newJobCreationRate: 25,
      displacementLow: 60,
      displacementMid: 45,
      displacementHigh: 15,
      displacementTimeline: 8,
      retrainingEffectiveness: 70,
      aiAccessIndex: 75,
      schoolAccessLow: 60,
      schoolAccessMid: 75,
      schoolAccessHigh: 85,
      geographicGap: 20,
      ubiEnabled: true,
      ubiAmount: 800,
      retrainingSubsidies: 60,
      robotTaxRate: 20,
      regulatoryBrakes: 0,
      safetyNet: 'strengthened',
    },
  },

  displacement_shock: {
    id: 'displacement_shock',
    name: 'Displacement Shock',
    message: 'Rapid automation with no safety net — the cascade scenario',
    description: 'Accelerated adoption with concentrated AI access, no policy response.',
    params: {
      adoptionRate: 80,
      adoptionCurve: 'accelerated',
      newJobCreationRate: 10,
      displacementLow: 85,
      displacementMid: 70,
      displacementHigh: 30,
      displacementTimeline: 3,
      retrainingEffectiveness: 15,
      aiAccessIndex: 25,
      schoolAccessLow: 10,
      schoolAccessMid: 35,
      schoolAccessHigh: 85,
      geographicGap: 70,
      ubiEnabled: false,
      ubiAmount: 0,
      retrainingSubsidies: 0,
      robotTaxRate: 0,
      regulatoryBrakes: 0,
      safetyNet: 'minimal',
    },
  },

  policy_intervention: {
    id: 'policy_intervention',
    name: 'Policy Intervention',
    message: 'Shows whether active policy meaningfully changes outcomes',
    description: 'Mid-speed adoption with all policy levers engaged at moderate intensity.',
    params: {
      adoptionRate: 55,
      adoptionCurve: 'gradual',
      newJobCreationRate: 20,
      displacementLow: 65,
      displacementMid: 50,
      displacementHigh: 20,
      displacementTimeline: 6,
      retrainingEffectiveness: 55,
      aiAccessIndex: 60,
      schoolAccessLow: 45,
      schoolAccessMid: 60,
      schoolAccessHigh: 80,
      geographicGap: 35,
      ubiEnabled: true,
      ubiAmount: 600,
      retrainingSubsidies: 60,
      robotTaxRate: 15,
      regulatoryBrakes: 1,
      safetyNet: 'strengthened',
    },
  },

  laissez_faire: {
    id: 'laissez_faire',
    name: 'Laissez-Faire',
    message: 'Free market automation — who wins, who loses',
    description: 'Fast adoption, no regulation, no policy response, minimal safety net.',
    params: {
      adoptionRate: 75,
      adoptionCurve: 'accelerated',
      newJobCreationRate: 20,
      displacementLow: 80,
      displacementMid: 65,
      displacementHigh: 25,
      displacementTimeline: 4,
      retrainingEffectiveness: 20,
      aiAccessIndex: 20,
      schoolAccessLow: 15,
      schoolAccessMid: 40,
      schoolAccessHigh: 90,
      geographicGap: 60,
      ubiEnabled: false,
      ubiAmount: 0,
      retrainingSubsidies: 5,
      robotTaxRate: 0,
      regulatoryBrakes: 0,
      safetyNet: 'minimal',
    },
  },

  children_first: {
    id: 'children_first',
    name: 'Children First',
    message: 'Highlights how AI access gaps in schools compound inequality over generations',
    description: 'Moderate adoption but heavily skewed school access between income tiers.',
    params: {
      adoptionRate: 50,
      adoptionCurve: 'gradual',
      newJobCreationRate: 18,
      displacementLow: 55,
      displacementMid: 45,
      displacementHigh: 18,
      displacementTimeline: 6,
      retrainingEffectiveness: 40,
      aiAccessIndex: 30,
      schoolAccessLow: 10,
      schoolAccessMid: 40,
      schoolAccessHigh: 90,
      geographicGap: 50,
      ubiEnabled: false,
      ubiAmount: 0,
      retrainingSubsidies: 30,
      robotTaxRate: 0,
      regulatoryBrakes: 0,
      safetyNet: 'current',
    },
  },

  current_trajectory: {
    id: 'current_trajectory',
    name: 'Current Trajectory',
    message: 'The realistic baseline — where we are headed without intervention',
    description: 'Parameters seeded from 2024 real-world data and current adoption projections.',
    params: {
      adoptionRate: 40,
      adoptionCurve: 'gradual',
      newJobCreationRate: 15,
      displacementLow: 55,
      displacementMid: 42,
      displacementHigh: 15,
      displacementTimeline: 7,
      retrainingEffectiveness: 30,
      aiAccessIndex: 42,
      schoolAccessLow: 25,
      schoolAccessMid: 55,
      schoolAccessHigh: 82,
      geographicGap: 40,
      ubiEnabled: false,
      ubiAmount: 0,
      retrainingSubsidies: 10,
      robotTaxRate: 0,
      regulatoryBrakes: 0,
      safetyNet: 'current',
    },
  },
};

export const PRESET_LIST = Object.values(PRESETS);
